version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - BEDROCK_MODEL_ID=anthropic.claude-3-haiku-20240307-v1:0
      - AWS_REGION=us-east-1
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend_service:8000   # ✅ used inside app.py
    depends_on:
      - backend
    restart: always
