version: "3.9"
services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - BEDROCK_MODEL_ID=anthropic.claude-3-haiku-20240307-v1:0
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
