name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Run format checks
        run: |
          black --check .
          isort --check-only --profile black .
          ruff check .

      - name: Build backend Docker image
        run: docker build -t backend ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./frontend

  deploy:
    needs: lint-and-build
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Cleanup runtime uploads folder
        run: |
          echo "Cleaning up uploads folder before checkout..."
          sudo rm -rf /home/ubuntu/actions-runner/_work/ml_ops_3/ml_ops_3/backend/data/uploads || true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment file
        run: |
          if [ ! -f backend/.env ]; then
            echo "No .env file found, copying from .env.example"
            cp backend/.env.example backend/.env
          fi

      - name: Stop old containers
        run: |
          echo "Stopping old containers..."
          docker compose -f docker-compose.yml down || true

      - name: Build and start containers
        run: |
          echo "Starting new containers..."
          docker compose -f docker-compose.yml up -d --build

      - name: Show container status
        run: docker compose -f docker-compose.yml ps

      - name: Backend logs
        run: docker compose -f docker-compose.yml logs backend --tail=100 || true

      - name: Frontend logs
        run: docker compose -f docker-compose.yml logs frontend --tail=100 || true
