name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Run format checks
        run: |
          black --check .
          isort --check-only --profile black .
          ruff check .

      - name: Build backend Docker image
        run: docker build -t backend ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./frontend

  deploy:
    needs: lint-and-build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old containers
        run: docker compose -f docker-compose.yml down || true

      - name: Build and start containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Show container status
        run: docker compose ps

      - name: Backend logs
        run: docker compose logs backend --tail=100

      - name: Frontend logs
        run: docker compose logs frontend --tail=100
