  deploy:
    needs: lint-and-build
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment file
        run: |
          if [ ! -f backend/.env ]; then
            echo "No .env file found, copying from .env.example"
            cp backend/.env.example backend/.env
          fi

      - name: Stop old containers
        run: |
          echo "Stopping old containers..."
          docker compose -f docker-compose.yml down || true

      - name: Build and start containers
        run: |
          echo "Starting new containers..."
          docker compose -f docker-compose.yml up -d --build

      - name: Show container status
        run: docker compose -f docker-compose.yml ps

      - name: Backend logs
        run: docker compose -f docker-compose.yml logs backend --tail=100 || true

      - name: Frontend logs
        run: docker compose -f docker-compose.yml logs frontend --tail=100 || true
